spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.kskmlal.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
server:
  port: ${SERVER_PORT:8081}
jwt:
  secret: 'e+VYNFyI6gw8NFxoBW5XcQM8fZhifDO2fk2Q3ylHHhKbh49Z81p+vbN4gvnr5jHLyDJdxvts2hZfxthxynjz3g+EJf2L7LOFkwKCUZpkVrI='
  expiration: 120000
  expiration-sec:
    refresh-token: 10